# Keep GitHub Actions up to date automatically
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5
