# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold #9ece6a)' # Tokyo Night green
error_symbol = '[➜](bold #f7768e)' # Tokyo Night red

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true