[tools]
elixir = "latest"
erlang = "latest"
go = "latest"
gradle = "latest"
groovy = "latest"
java = "lts"
kotlin = "latest"
lua = "5.1"
maven = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
